project:
  type: website

website:
  title: "Analytics Corner"
  image: "uhc.png"
  favicon: "favicon.png"
  repo-url: https://github.com/Drexel-UHC/analytics-corner
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    background: light
    logo: uhc.png
    logo-alt: "Drexel dragon logo."
    collapse-below: lg
    left:
      - text: "Overview" 
        href: index.qmd
      - text: Manuals
        menu:
        - href: pages/manuals/welcome/1-about.qmd
          text: "Welcome"
        - href: pages/manuals/git-github/overview.qmd
          text: "Git and GitHub"
        - href: pages/manuals/dbt/overview.qmd
          text: "Datawarehousing + DBT"
      - text: "Blog"
        href: pages/blog/index.qmd
      - text: "Gallery"
        href: pages/gallery/index.qmd
      - text: "Help"
        menu:
          - text: "Submit an Issue"
            icon: "patch-question"
            href: "https://github.com/Drexel-UHC/analytics-core/issues/new?assignees=&labels=&template=request.yml&title=%5BRequest+title%5D%3A+"
          - text: "View Discussions"
            icon: "chat-right-text"
            href: "https://github.com/Drexel-UHC/analytics-core/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: pages/faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/drexeluhc
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/Drexel-UHC/analytics-core
        aria-label: Quarto GitHub
        
  page-footer:
    center:
      - text: 'About'
        href: about.qmd
      - text: 'FAQ'
        href: pages/faq/index.qmd
      - text: 'License'
        href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/drexeluhc
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/Drexel-UHC/analytics-core
        aria-label: Quarto GitHub
        
  sidebar:
    - id: dbt
      contents:
        - text: 'Overview'
          href: pages/manuals/dbt/overview.qmd
        - text: "---"
        - section: 'Basics'
          contents:
          - text: '1. Get started'
            href: pages/manuals/dbt/get-started-install.qmd    
          - text: '2. Loading Data'
            href: pages/manuals/dbt/load-data.qmd   
          - text: '3. Basic Modeling'
            href: pages/manuals/dbt/basic-modeling.qmd   
          - text: '4. Documentation'
            href: pages/manuals/dbt/documentation.qmd    
        - section: 'Fundamental DBT'
          contents:
          - text: '5. Data Modeling'
            href: pages/manuals/dbt/data-modeling.qmd    
          - text: '6. Macros: DBT functional programming'
            href: pages/manuals/dbt/functional-programming.qmd    
          - text: '7. Work in the cloud'
            href: pages/manuals/dbt/work-in-cloud.qmd    
    - id: git-github
      contents:
        - text: 'Overview'
          href: pages/manuals/git-github/overview.qmd
        - text: "---"
        - section: 'Why learn Git/GitHub?'
          contents:
          - text: '1. Version Control'
            href: pages/manuals/git-github/case-study-version-control.qmd
          - text: '2. Project organization'
            href: pages/manuals/git-github/case-study-project-transition-management.qmd
          - text: '3. Precedent'
            href: pages/manuals/git-github/precedent.qmd
          - text: '4. TLDR'
            href: pages/manuals/git-github/why-summary.qmd
        - section: 'How to Git/GitHub?'
          contents:
          - text: 'Teaching philosophy'
            href: pages/manuals/git-github/teaching-thoughts.qmd
          - text: 'Learning Objectives'
            href: pages/manuals/git-github/learning-objectives.qmd
          - text: 'Git Intro'
            href: pages/manuals/git-github/git-intro.qmd
          - text: 'Basic Git Workflow'
            href: pages/manuals/git-github/git-basics.qmd
          - text: 'Git vs GitHub'
            href: pages/manuals/git-github/git-vs-github.qmd
          - text: 'Git vs Github Desktop'
            href: pages/manuals/git-github/git-vs-github-desktop.qmd
          - text: 'Setup GitHub Desktop'
            href: pages/manuals/git-github/install-github-desktop.qmd
          - text: '1. init - create a new repo remotely'
            href: pages/manuals/git-github/init.qmd
          - text: '2. clone - copy online repo to local computer'
            href: pages/manuals/git-github/clone.qmd
          - text: '3. status - file changes of local repo'
            href: pages/manuals/git-github/status.qmd
    - id: welcome
      contents:
        - section: 'Manual: Welcome'
          contents:
          - text: '1. About'
            href: pages/manuals/welcome/1-about.qmd
          - text: '2. Core values'
            href: pages/manuals/welcome/2-core-values.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true
