project:
  type: website

website:
  title: "Analytics Corner"
  image: "uhc.png"
  favicon: "favicon.png"
  navbar:
    background: light
    logo: uhc.png
    logo-alt: "Drexel dragon logo."
    collapse-below: lg
    left:
      - text: "Overview" 
        href: index.qmd
      - text: "Get Started"
        href: docs/get-started/index.qmd
      - text: "Blog"
        href: docs/blog/index.qmd
      - text: "Gallery"
        href: docs/gallery/index.qmd
      - text: "Help"
        menu:
          - text: "Submit an Issue"
            icon: "patch-question"
            href: "https://github.com/Drexel-UHC/analytics-core/issues/new?assignees=&labels=&template=request.yml&title=%5BRequest+title%5D%3A+"
          - text: "View Discussions"
            icon: "chat-right-text"
            href: "https://github.com/Drexel-UHC/analytics-core/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: docs/faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/drexeluhc
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/Drexel-UHC/analytics-core
        aria-label: Quarto GitHub
format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true
