project:
  type: website

website:
  title: "UHC Analytics"
  image: "uhc.png"
  navbar:
    background: light
    logo: uhc.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



