project:
  type: website

website:
  title: "Analytics Corner"
  image: "uhc.png"
  favicon: "favicon.png"
  repo-url: https://github.com/Drexel-UHC/analytics-corner
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    background: light
    logo: uhc.png
    logo-alt: "Drexel dragon logo."
    collapse-below: lg
    left:
      - text: "Overview" 
        href: index.qmd
      - text: Manuals
        menu:
        - href: docs/manuals/welcome/1-about.qmd
          text: "Welcome"
        - href: docs/manuals/git-github/overview.qmd
          text: "Git and GitHub"
      - text: "Blog"
        href: docs/blog/index.qmd
      - text: "Gallery"
        href: docs/gallery/index.qmd
      - text: "Help"
        menu:
          - text: "Submit an Issue"
            icon: "patch-question"
            href: "https://github.com/Drexel-UHC/analytics-core/issues/new?assignees=&labels=&template=request.yml&title=%5BRequest+title%5D%3A+"
          - text: "View Discussions"
            icon: "chat-right-text"
            href: "https://github.com/Drexel-UHC/analytics-core/discussions"
          - text: "FAQ"
            icon: "question-circle"
            href: docs/faq/index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/drexeluhc
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/Drexel-UHC/analytics-core
        aria-label: Quarto GitHub
        
  page-footer:
    center:
      - text: 'About'
        href: about.qmd
      - text: 'FAQ'
        href: docs/faq/index.qmd
      - text: 'License'
        href: license.qmd
    right:
      - icon: twitter
        href: https://twitter.com/drexeluhc
        aria-label: Quarto Twitter
      - icon: github
        href: https://github.com/Drexel-UHC/analytics-core
        aria-label: Quarto GitHub
        
  sidebar:
    - id: git-github
      contents:
        - text: 'Overview'
          href: docs/manuals/git-github/overview.qmd
        - text: "---"
        - section: 'Why learn Git/GitHub?'
          contents:
          - text: '1. Version Control'
            href: docs/manuals/git-github/case-study-version-control.qmd
          - text: '2. Project organization'
            href: docs/manuals/git-github/case-study-project-transition-management.qmd
          - text: '3. Precedent'
            href: docs/manuals/git-github/precedent.qmd
          - text: '4. TLDR'
            href: docs/manuals/git-github/why-summary.qmd
        - section: 'How to Git/GitHub?'
          contents:
          - text: '1. Teaching philosophy'
            href: docs/manuals/git-github/teaching-thoughts.qmd
          - text: '2. Learning Objectives'
            href: docs/manuals/git-github/learning-objectives.qmd
          - text: '3. Git vs GitHub'
            href: docs/manuals/git-github/git-vs-github.qmd
          - text: '4. Git vs Github Desktop'
            href: docs/manuals/git-github/git-vs-github-desktop.qmd
          - text: '5. Setup GitHub Desktop'
            href: docs/manuals/git-github/install-github-desktop.qmd
    - id: welcome
      contents:
        - section: 'Manual: Welcome'
          contents:
          - text: '1. About'
            href: docs/manuals/welcome/1-about.qmd
          - text: '2. Core values'
            href: docs/manuals/welcome/2-core-values.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true
