name: Request
description: File a request
body:
  - type: markdown
    attributes:
      value: |
        > **Warning** The idea of an analytics core is to serve as a centralized analytics resource for the UHC and Dornsife community.  This repository something that is not official in any capacity (yet) and is just something @rl627 is testing to keep things organized as request volume is increasing. 

        ---

        Thank you for taking the time to file a request. We will reach out soon within one or two business days.
  - type: input
    id: name
    attributes:
      label: Name
      description: "What is your name"
      placeholder: "Samwise Gamgee"
    validations:
      required: true
